#<% require 'kitchen-sync' %>
---
provisioner:
  name: chef_zero
  chef_omnibus_url: https://www.chef.io/chef/install.sh

platforms:
  - name: vagrant-ubuntu-14.04
    driver:
      name: vagrant
      box: ubuntu-1404
      box_url: "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
      box_sha1: 227e3a68fd7460a9bafcc59af208fa64994ae298e1187e5e0b3d987759128a99 
      customize:
        nictype1: virtio

suites:
  - name: default
    run_list:
      - recipe[company-news]
    #roles_path: test/fixtures/roles
    #data_bags_path: test/fixtures/data_bags
