---
driver:
  name: ec2
  aws_ssh_key_id: "<%= ENV['AWS_SSH_KEY_ID']%>"
  region: ap-northeast-1
  availability_zone: ap-northeast-1c
  require_chef_omnibus: true
  associate_public_ip: true

  transport:
    ssh_key: "<%= ENV['AWS_SSH_KEY']%>"

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      image_id: ami-8d6d9d8d
